_target_: lightning.pytorch.trainer.Trainer

max_epochs: 100
accelerator: auto
devices: auto
strategy: auto

callbacks:
  - _target_: lightning.pytorch.callbacks.ModelCheckpoint
    monitor: "val/accuracy"
    mode: "max"
    save_top_k: 3
    filename: "best-{epoch:02d}-{val/accuracy:.4f}"
    save_last: true
  
  - _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: "val/accuracy"
    mode: "max"
    patience: 20
    min_delta: 0.001
  
  - _target_: lightning.pytorch.callbacks.LearningRateMonitor
    logging_interval: "step"
  
  - _target_: lightning.pytorch.callbacks.RichProgressBar

precision: "16-mixed"
gradient_clip_val: 1.0
accumulate_grad_batches: 1
log_every_n_steps: 50