_target_: lightning.pytorch.loggers.WandbLogger

project: "wave-breaking-distillation"
name: null
save_dir: "./logs"
log_model: true
tags:
  - "knowledge_distillation"
  - "wave_breaking"
  - "dinov2"
  - "vit_lstm"