defaults:
  - model: distillation
  - data: wave_breaking_enhanced
  - trainer: default
  - logger: wandb
  - _self_

# Global settings
seed: 42
experiment_name: "wave_breaking_distillation"


# Override defaults
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}